{{- if and .PullSecretName .PullSecretDockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .PullSecretName }}
  namespace: {{ .AddonInstallNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .PullSecretDockerConfigJson }}
{{- end }}
