apiVersion: v2
name: flower-addon
description: Flower Federated Learning addon for Open Cluster Management
type: application
version: 0.1.0
appVersion: "1.25.0"
keywords:
  - federated-learning
  - flower
  - ocm
  - open-cluster-management
  - machine-learning
home: https://github.com/stolostron/flower-addon
sources:
  - https://github.com/stolostron/flower-addon
maintainers:
  - name: yanmxa
    email: myan@redhat.com
