apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: AddOnPlacementScore
metadata:
  name: example-powerconsumption-score
  namespace: cluster1
status:
  scores:
  - name: app01;all
    value: 20
  - name: app02;all
    value: 25
  - name: app01;3g.48gb
    value: 40
  - name: app02;3g.48gb
    value: 55
  - name: app01;2g.24gb
    value: 70
  - name: app02;2g.24gb
    value: 80
