apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: {{.ManifestName}}
  namespace: {{.ManifestNamespace}}
spec:
  manifestConfigs:
    - resourceIdentifier:
        group: batch
        resource: jobs
        namespace: {{ .ClientJobNamespace }}
        name: {{ .ClientJobName }}
      updateStrategy:
        type: ServerSideApply
  deleteOption:
    propagationPolicy: SelectivelyOrphan
    selectivelyOrphans:
      orphaningRules:
      - group: ""
        resource: namespaces
        name: {{ .ClientJobNamespace }}
  workload:
    manifests:
      - kind: Namespace
        apiVersion: v1
        metadata:
          name: {{.ClientJobNamespace}}
      - kind: Job
        apiVersion: batch/v1
        metadata:
          name: {{ .ClientJobName }}
          namespace: {{ .ClientJobNamespace }}
        spec:
          selector: # Match the labels in the pod template
            matchLabels:
              job-name: {{ .ClientJobName }}
          template:
            metadata:
              labels:
                job-name: {{ .ClientJobName }} # Ensure labels match the selector
            spec:
              shareProcessNamespace: true
              volumes:
                - name: metric-data
                  emptyDir: {}

              containers:
              - name: flower-client
                image: {{ .ClientJobImage }}
                imagePullPolicy: Always
                args:
                - client # Maps to the entrypoint.sh logic
                - --data-config={{ .ClientDataConfig }}
                - --server-address={{ .ServerAddress }}
                volumeMounts:
                  - name: metric-data
                    mountPath: /metrics
              
              {{- if .ObsSidecarImage }}
              - name: obs-sidecar
                image: {{ .ObsSidecarImage }}
                imagePullPolicy: Always
                args:
                  - -metricfile=/metrics/metric.json
                  - -endpoint=$(OTEL_ENDPOINT)
                volumeMounts:
                  - name: metric-data
                    mountPath: /metrics
                env:
                  # The default endpoint for the Open Cluster Management observability service.
                  # Change this value to your otel collector endpoint if you are not using the OCM observability service.
                  - name: OTEL_ENDPOINT
                    value: "otel-collector.open-cluster-management-agent-addon.svc.cluster.local:4317"
                  - name: POD_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
              {{- end }}
              restartPolicy: Never
