apiVersion: work.open-cluster-management.io/v1alpha1
kind: ManifestWorkReplicaSet
metadata:
  name: mwrs-app02
  namespace: default
  labels:
    app: "app02"
    resource-request-kind: "gpu"
    resource-request-amount: "2"
spec:
  placementRefs:
    - name: app02-placement
      rolloutStrategy:
        rolloutType: All
  manifestWorkTemplate:
    workload:
      manifests:
      - apiVersion: v1
        kind: Pod
        metadata:
          name: app02-pod
          namespace: default
          labels:
            app: app02
        spec:
          containers:
          - name: sleep
            image: busybox:1.36
            command: ["sh", "-c", "sleep 3600"]
            resources:
              requests:
                cpu: "1"
                memory: "256Mi"
              limits:
                cpu: "2"
                memory: "512Mi"