apiVersion: work.open-cluster-management.io/v1alpha1
kind: ManifestWorkReplicaSet
metadata:
  name: mwrs-app01
  namespace: default
  labels:
    app: "app01"
    resource-request-kind: "gpu"
    resource-request-amount: "2"
spec:
  placementRefs:
    - name: app01-placement
      rolloutStrategy:
        rolloutType: All
  manifestWorkTemplate:
    workload:
      manifests:
      - apiVersion: v1
        kind: Pod
        metadata:
          name: app01-pod
          namespace: default
          labels:
            app: app01
        spec:
          containers:
          - name: sleep
            image: busybox:1.36
            command: ["sh", "-c", "sleep 3600"]
            resources:
              requests:
                cpu: "1"
                memory: "256Mi"
              limits:
                cpu: "2"
                memory: "512Mi"