apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: addon-manager-controller-rolebinding
  namespace: open-cluster-management-hub
subjects:
- kind: ServiceAccount
  name: addon-manager-controller-sa
  namespace: open-cluster-management-hub
roleRef:
  kind: Role
  name: addon-manager-controller-role
  apiGroup: rbac.authorization.k8s.io
