kind: Deployment
apiVersion: apps/v1
metadata:
  name: dynamic-scoring-addon-controller
  labels:
    app: dynamic-scoring-addon-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-scoring-addon-controller
  template:
    metadata:
      labels:
        app: dynamic-scoring-addon-controller
    spec:
      serviceAccountName: dynamic-scoring-addon-sa
      containers:
      - name: dynamic-scoring-addon-controller
        image: quay.io/open-cluster-management/dynamic-scoring-addon
        imagePullPolicy: IfNotPresent
        args:
          - "/dynamic-scoring-addon"
          - "controller"
