apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: dynamic-scoring-addon-config-aarch64
  namespace: open-cluster-management
spec:
  agentInstallNamespace: dynamic-scoring
  customizedVariables:
    - name: Image
      value: default-route-openshift-image-registry.apps.hubdev01.airan.localdomain/open-cluster-management/dynamic-scoring-addon:latest-aarch64
    - name: ImagePullSecrets
      value: '["hub-registry-secret"]'