apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: global-aarch64
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: cluster-arch
              operator: In
              values:
                - aarch64
