apiVersion: v2
name: dynamic-scoring-framework
description: A Helm chart for Open Cluster Management Dynamic Scoring Framework Addon
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: KA-Takeuchi
    email: KA-Takeuchi@example.com
