apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: dynamic-scoring-framework
spec:
  addOnMeta:
    displayName: dynamic-scoring-framework
    description: "Centralized scoring logic management and distribution agent for Open Cluster Management multi-cluster environments"
  supportedConfigs:
    - group: addon.open-cluster-management.io
      resource: addondeploymentconfigs
  installStrategy:
    type: Placements
    placements:
      - name: dynamic-scoring-placement
        namespace: {{ .Values.hubSetting.namespace }}
        configs:
          - group: addon.open-cluster-management.io
            resource: addondeploymentconfigs
            name: dynamic-scoring-addon-config
            namespace: {{ .Values.hubSetting.namespace }}
      - name: dynamic-scoring-placement-aarch64
        namespace: {{ .Values.hubSetting.namespace }}
        configs:
          - group: addon.open-cluster-management.io
            resource: addondeploymentconfigs
            name: dynamic-scoring-addon-config-aarch64
            namespace: {{ .Values.hubSetting.namespace }}