apiVersion: dynamic-scoring.open-cluster-management.io/v1alpha1
kind: DynamicScoringConfig
metadata:
  name: dynamic-scoring-config
spec:
  masks:
    - clusterName: "worker02"
      scoreName: "llm_forecast_score"