# This rule is not used by the project dynamic-scoring-framework itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the dynamic-scoring.open-cluster-management.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dynamic-scoring-framework
    app.kubernetes.io/managed-by: kustomize
  name: dynamicscorer-editor-role
rules:
- apiGroups:
  - dynamic-scoring.open-cluster-management.io
  resources:
  - dynamicscorers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dynamic-scoring.open-cluster-management.io
  resources:
  - dynamicscorers/status
  verbs:
  - get
