apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: addon-aarch64-build
  namespace: dynamic-scoring
spec:
  strategy:
    type: Docker
    dockerStrategy:
      pullSecret:
          name: dockerhub-secret
      dockerfilePath: Dockerfile.addon
  source:
    type: Binary
  output:
    to:
      kind: DockerImage
      name: >-
        default-route-openshift-image-registry.apps.hubdev01.airan.localdomain/open-cluster-management/dynamic-scoring-addon:latest-aarch64
    pushSecret:
      name: hub-push-secret